### ISSUE TITLE
extract_segment_level.main

### ISSUE THREAD

**Issue by dangvansam98** [eesungkim/Speech_Emotion_Recognition_DNN-ELM#3]
==================================================
Total Session_1 : 564
{'ang': 167, 'sur': 0, 'dis': 0, 'fea': 0, 'hap': 102, 'fru': 0, 'xxx': 0, 'exc': 44, 'sad': 90, 'neu': 161}
==================================================
Completed to save session_1 Wave files successfully.
==================================================
Total Session_2 : 493
{'ang': 115, 'sur': 0, 'dis': 0, 'fea': 0, 'hap': 63, 'fru': 0, 'xxx': 0, 'exc': 73, 'sad': 97, 'neu': 145}
==================================================
Completed to save session_2 Wave files successfully.
==================================================
Total Session_3 : 524
{'ang': 150, 'sur': 0, 'dis': 0, 'fea': 0, 'hap': 75, 'fru': 0, 'xxx': 0, 'exc': 62, 'sad': 115, 'neu': 122}
==================================================
Completed to save session_3 Wave files successfully.
==================================================
Total Session_4 : 497
{'ang': 243, 'sur': 0, 'dis': 0, 'fea': 0, 'hap': 34, 'fru': 0, 'xxx': 0, 'exc': 74, 'sad': 62, 'neu': 84}
==================================================
Completed to save session_4 Wave files successfully.
==================================================
Total Session_5 : 510
{'ang': 139, 'sur': 0, 'dis': 0, 'fea': 0, 'hap': 37, 'fru': 0, 'xxx': 0, 'exc': 125, 'sad': 112, 'neu': 97}
==================================================
Completed to save session_5 Wave files successfully.
==================================================
Extracting segment-level features......................
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    extract_segment_level.main(ROOT_PATH,MODIFIED_DATASETS_PATH,MODEL_NAME,nFolders,segmentNum)
  File "D:\SER\Speech_Emotion_Recognition_DNN-ELM-master\models\extract_segment_level.py", line 249, in main
    extract_segment_level_features(subdir, MODEL_PATH, idx, segmentNum)
  File "D:\SER\Speech_Emotion_Recognition_DNN-ELM-master\models\extract_segment_level.py", line 65, in extract_segment_level_features
    featSegment,segNum = extract_lowlevel_features(audio_path, segmentNum)
  File "D:\SER\Speech_Emotion_Recognition_DNN-ELM-master\models\extract_segment_level.py", line 38, in extract_lowlevel_features
    pitch_based=pitch_based_features(signal, fs, win_length=400, hop_length=160)
  File "D:\SER\Speech_Emotion_Recognition_DNN-ELM-master\utils\speech_features.py", line 373, in pitch_based_features
    ceps = _cepstrum(samples_in_window,win_length,hop_length)
  File "D:\SER\Speech_Emotion_Recognition_DNN-ELM-master\utils\speech_features.py", line 344, in _cepstrum
    y[win_start+j]=y[win_start+j]*window[j]
ValueError: assignment destination is read-only

**Comment by dangvansam98** [comment]
have error: ValueError: assignment destination is read-only

**Comment by TythonLee** [comment]
> have error: ValueError: assignment destination is read-only

Have you resolved this issue?
